version: '3'

services:
  container-name:
    image: arpnghosh/eximage  
    ports:
      - "8000:8000"
    volumes:
      - "./:/home/app"
    env_file:
      - "./.env"
    container_name: excontainer
    restart: "no"
